# The schema version of your toml file. DO NOT CHANGE THIS.
modLoader="javafml" # Specifies Forge's mod loader.
loaderVersion="[1,)" # Loader version range, ensure compatibility with your Forge version (e.g., 1.20.1).
license="All rights reserved" # Your mod's license, or "All rights reserved" as a default.
##issueTrackerURL="https://github.com/Malware98/BrokenPath/issues" # Optional: Link to your bug tracker (e.g., GitHub Issues).

# Define the Minecraft version for which your mod is built.
# The version range indicates that your mod will load in any Minecraft version
# from 1.20.1 (inclusive) up to the next major version (exclusive).
# Example: "[1.20.1,1.21)" works for 1.20.1, 1.20.2, etc., but not 1.21.
# For 1.20.1 exclusively: "[1.20.1,1.20.2)".
minecraft_version="[1.20.1,1.20.2)" # The specific Minecraft version this mod targets.

# --- Mod Definition ---
[[mods]] # Defines a new mod object; typically only one per toml file.
modId="brokenpath" # YOUR UNIQUE MOD ID. MUST MATCH BrokenPath.MOD_ID in your code.
version="0.1-1.20.1" # The current version of your mod, ideally following SemVer (Major.Minor.Patch).
displayName="Broken Path" # The visible name of your mod in-game.
##updateJSONURL="" # Optional: URL to a JSON file for automatic updates.
##logoFile="logo.png" # Optional: Path to your mod's logo image (place in src/main/resources).
credits="Made by Malware98" # Credits for contributors.
authors="Malware98" # Main authors of the mod.

description='''
The forge of the gods created races, war drew borders, and now... your choice breaks the cycle.

Broken Path | Even broken paths lead to glory.
''' # A brief description of your mod, displayed in-game.


# --- Optional: Mod Dependencies ---
# Dependencies define other mods your mod requires to run.

# Example Forge dependency:
# [[dependencies.brokenpath]]
# modId="forge"         # The ID of the dependency (Forge itself).
# mandatory=true        # Specifies if this dependency is required.
# versionRange="[47.0.0,)" # Adjust this range to the specific Forge version for 1.20.1 you are using.
# ordering="NONE"       # Controls load order relative to this mod. "NONE" means no specific order.
# side="BOTH"           # Indicates if the dependency is required on client, server, or both.

# Example Minecraft dependency:
# [[dependencies.brokenpath]]
# modId="minecraft"     # The ID of Minecraft itself.
# mandatory=true
# versionRange="[1.20.1,1.20.2)" # The Minecraft version range your mod supports.
# ordering="NONE"
# side="BOTH"